Repository tiemonl/PitStopBot, pull requests merged in 2019-05, with the labels that each got.

#3 Add random draw giveaway feature
  .gitattributes
  .gitignore
  PitStopBot.sln
  PitStopBot/Commands/GeneralCommands.cs
  PitStopBot/Commands/GiveawayCommands.cs
  PitStopBot/GetKey.cs
  PitStopBot/Logger.cs
  PitStopBot/PitStopBot.cs
  PitStopBot/PitStopBot.csproj
  PitStopBot/Utils/GiveawayUtils.cs
Labels: enhancement

#10 Add community guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  LICENSE.md
  README.md
Labels: enhancement

#19 Added the ability to view part info
  PitStopBot/Commands/PartInfoCommands.cs
  PitStopBot/Objects/Inventory.cs
  PitStopBot/Objects/Part.cs
  PitStopBot/Utils/PartInfoUtils.cs
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#20 Added ability to use ENS address
  PitStopBot/Commands/UserInfoCommands.cs
  PitStopBot/GetKey.cs
  PitStopBot/Objects/ENS.cs
  PitStopBot/PitStopBot.csproj
  PitStopBot/Utils/EnsUtils.cs
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#23 Added inventory brand count
  PitStopBot/Commands/UserInfoCommands.cs
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#25 Added guidance for users with a bad ens set up
  PitStopBot/Commands/UserInfoCommands.cs
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#26 Added multi instance capability for giveaway + fixed async command issue
  PitStopBot/Commands/GiveawayCommands.cs
  PitStopBot/Utils/GiveawayInstance.cs
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#28 Added the total inventory part count to messages
  PitStopBot/Commands/UserInfoCommands.cs
Labels: Priority: Low, Status: Completed, Type: Enhancement

#29 GH-27 Added cancel feature in giveaway + modified rate of modify async message to 5 seconds
  PitStopBot/Commands/GiveawayCommands.cs
  PitStopBot/Utils/GiveawayInstance.cs
Labels: Priority: Low, Status: Completed, Type: Enhancement

#34 Added a dynamic help command
  PitStopBot/Commands/GeneralCommands.cs
  PitStopBot/Commands/GiveawayCommands.cs
  PitStopBot/Commands/PartInfoCommands.cs
  PitStopBot/Commands/UserInfoCommands.cs
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#35 Removed bot prompt at start up
  PitStopBot/PitStopBot.cs
Labels: Priority: Low, Status: Completed, Type: Maintenance
